L = ['int(\'101\', 2) = 3', 'L.insert(idx, el)', 'index,find.(el,i,j)']
L += ['all(x): 모두 참, all([])= T', 'any(x): 모두 거짓, any([])= F' ]
L += ['round(n, 자릿수)', '{a:_<n.xf}', 'bin(n)[2:]', 'list(filter(f, L))']
L += ['','from sys import *', 'exit()']
L += ['','from random import*','random()# 0.0~1.0', 'randint(a,b)', 'shuffle(data)']
L += ['','from math import *', 'sqrt(n)']
L += ['','from queue import PriorityQueue as pq', 'Q = pq()', 'Q.put(4)', 'Q.get()']
L += ['', 'from functools import cmp_to_key as cmp', 'L.sort(key=cmp(lambda a, b:)) ']
L += ['', 'from operator import itemgetter', 'L.sort(key= itemgetter(1,0)) ']
L += ['', 'L= [int(input()) for i in [0]*int(input())]']
L += ['', 'import queue as Q','q = Q.PriorityQueue()']
L += ['', 'from heapq import heappush, heappop', 'heappush(q, el)', 'heappop(q)']
L += ['', 'from fractions import *', 'Fraction(a,b)']
L += ['', 'python a.py > test3.txt', 'from sys import *', 'stdin = open("test.txt","r")']
L += ['', "UnicodeDecodeError: 'cp949'" , '다른 이름으로 저장 -> 인코딩 ANSI' ]
L += ['', 'import sys; s= sys.stdin.readline','s().split()', 's().rstrip()']
L += ['', 'from time import*','start=time()', 'print("time :", time()-start)']
L += ['', 'import sys', 'f = sys.stdin', 'while True: input = f.readline() if not input: break', ]
L += ['', 'EOF', 'for L in stdin:']
L += ['', 'from collections import deque', 'D = deque()']
[print(' ',i) for i in L]